// This file is generated by zbuild. Do not edit manually.

const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    const module_zbuild = b.createModule(.{
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
    });
    b.modules.put(b.dupe("zbuild"), module_zbuild) catch @panic("OOM");

    const exe_zbuild = b.addExecutable(.{
        .name = "zbuild",
        .root_module = module_zbuild,
    });

    const install_exe_zbuild = b.addInstallArtifact(exe_zbuild, .{
    });

    const tls_install_exe_zbuild = b.step("build-exe:zbuild", "Install the zbuild executable");
    tls_install_exe_zbuild.dependOn(&install_exe_zbuild.step);
    b.getInstallStep().dependOn(&install_exe_zbuild.step);

    const run_exe_zbuild = b.addRunArtifact(exe_zbuild);
    if (b.args) |args| run_exe_zbuild.addArgs(args);
    const tls_run_exe_zbuild = b.step("run:zbuild", "Run the zbuild executable");
    tls_run_exe_zbuild.dependOn(&run_exe_zbuild.step);

    const tls_run_test = b.step("test", "Run all tests");

    const test_zbuild = b.addTest(.{
        .name = "zbuild",
        .root_module = module_zbuild,
        .filters = &[_][]const u8{  },
    });
    const install_test_zbuild = b.addInstallArtifact(test_zbuild, .{});
    const tls_install_test_zbuild = b.step("build-test:zbuild", "Install the zbuild test");
    tls_install_test_zbuild.dependOn(&install_test_zbuild.step);

    const run_test_zbuild = b.addRunArtifact(test_zbuild);
    const tls_run_test_zbuild = b.step("test:zbuild", "Run the zbuild test");
    tls_run_test_zbuild.dependOn(&run_test_zbuild.step);
    tls_run_test.dependOn(&run_test_zbuild.step);

    const module_sync = b.createModule(.{
        .root_source_file = b.path("test/sync.zig"),
        .target = target,
        .optimize = optimize,
    });
    b.modules.put(b.dupe("sync"), module_sync) catch @panic("OOM");

    const test_sync = b.addTest(.{
        .name = "sync",
        .root_module = module_sync,
        .filters = &[_][]const u8{  },
    });
    const install_test_sync = b.addInstallArtifact(test_sync, .{});
    const tls_install_test_sync = b.step("build-test:sync", "Install the sync test");
    tls_install_test_sync.dependOn(&install_test_sync.step);

    const run_test_sync = b.addRunArtifact(test_sync);
    const tls_run_test_sync = b.step("test:sync", "Run the sync test");
    tls_run_test_sync.dependOn(&run_test_sync.step);
    tls_run_test.dependOn(&run_test_sync.step);

    module_sync.addImport("zbuild", module_zbuild);

}
