//! Generate a build.zig file from a Config

const std = @import("std");

const Config = @import("Config.zig");
const ConfigBuildgen = @This();

const Writer = std.io.AnyWriter;

allocator: std.mem.Allocator,
config: Config,
writer: Writer,

options: std.StringArrayHashMap(Option),
options_modules: std.StringArrayHashMap(Config.OptionsModule),
modules: std.StringArrayHashMap(Config.Module),
dependencies: std.StringArrayHashMap(void),

const Option = struct {
    type_name: []const u8,
    optional: bool,
};

pub fn init(allocator: std.mem.Allocator, config: Config, writer: Writer) ConfigBuildgen {
    return ConfigBuildgen{
        .allocator = allocator,
        .config = config,
        .writer = writer,
        .options = std.StringArrayHashMap(Option).init(allocator),
        .options_modules = std.StringArrayHashMap(Config.OptionsModule).init(allocator),
        .modules = std.StringArrayHashMap(Config.Module).init(allocator),
        .dependencies = std.StringArrayHashMap(void).init(allocator),
    };
}

pub fn deinit(self: *ConfigBuildgen) void {
    self.modules.deinit();
    self.dependencies.deinit();
}

pub fn write(self: *ConfigBuildgen) !void {
    try self.writeLn(
        \\// This file is generated by zbuild. Do not edit manually.
        \\
        \\const std = @import("std");
        \\
        \\pub fn build(b: *std.Build) void {{
        \\    const target = b.standardTargetOptions(.{{}});
        \\    const optimize = b.standardOptimizeOption(.{{}});
        \\
    ,
        .{},
        .{ .indent = 0 },
    );

    // add all config items without linking depends_on or imports

    if (self.config.dependencies) |dependencies| {
        try self.writeItems(Config.Dependency, writeDependency, dependencies.map);
    }
    if (self.config.options) |options| {
        try self.writeItems(Config.Option, writeOption, options.map);
    }
    if (self.config.options_modules) |options_modules| {
        try self.writeItems(Config.OptionsModule, writeOptionsModule, options_modules.map);
    }
    if (self.config.modules) |modules| {
        try self.writeItems(Config.Module, writeModule, modules.map);
    }
    if (self.config.executables) |executables| {
        try self.writeItems(Config.Executable, writeExecutable, executables.map);
    }
    if (self.config.libraries) |libraries| {
        try self.writeItems(Config.Library, writeLibrary, libraries.map);
    }
    if (self.config.objects) |objects| {
        try self.writeItems(Config.Object, writeObject, objects.map);
    }

    if ((self.config.tests != null and self.config.tests.?.map.count() > 0) or self.modules.count() > 0) {
        try self.writeLn(
            \\const run_tls_test = b.step("test", "Run all tests");
            \\
        , .{}, .{});
    }
    // ensure a test is created for every module in the project, not just explicitly defined tests
    for (self.modules.keys()) |name| {
        if (self.config.tests == null or !self.config.tests.?.map.contains(name)) {
            try self.writeTest(name, .{
                .root_module = .{ .value = .{ .name = name } },
                .filters = &.{},
            });
            try self.writer.writeAll("\n");
        }
    }
    if (self.config.tests) |tests| {
        try self.writeItems(Config.Test, writeTest, tests.map);
    }
    if (self.config.fmts) |fmts| {
        try self.writeLn(
            \\const run_tls_fmt = b.step("fmt", "Run all fmts");
            \\
        , .{}, .{});
        try self.writeItems(Config.Fmt, writeFmt, fmts.map);
    }
    if (self.config.runs) |runs| {
        try self.writeItems(Config.Run, writeRun, runs.map);
    }

    // link all imports

    if (self.config.modules) |modules| {
        try self.writeImports(Config.Module, modules.map);
    }
    if (self.config.executables) |executables| {
        try self.writeImports(Config.Executable, executables.map);
    }
    if (self.config.libraries) |libraries| {
        try self.writeImports(Config.Library, libraries.map);
    }
    if (self.config.objects) |objects| {
        try self.writeImports(Config.Object, objects.map);
    }
    if (self.config.tests) |tests| {
        try self.writeImports(Config.Test, tests.map);
    }
    // make sure all unused variables are used
    // target and optimize that aren't used (when all modules define them)
    var target_unused = true;
    var optimize_unused = true;
    for (self.modules.values()) |module| {
        if (module.target == null) {
            target_unused = false;
        }
        if (module.optimize == null) {
            optimize_unused = false;
        }
    }
    if (target_unused) {
        try self.writeLn("_ = target;", .{}, .{});
    }
    if (optimize_unused) {
        try self.writeLn("_ = optimize;", .{}, .{});
    }
    // options modules and dependencies that aren't imported
    for (self.options_modules.keys()) |name| {
        var options_module_unused = true;
        blk: for (self.modules.values()) |module| {
            if (module.imports) |imports| {
                for (imports) |import| {
                    if (std.mem.eql(u8, name, import)) {
                        options_module_unused = false;
                        break :blk;
                    }
                }
            }
        }
        if (options_module_unused) {
            try self.writeLn("_ = options_module_{s};", .{name}, .{});
        }
    }
    for (self.dependencies.keys()) |name| {
        var dependency_unused = true;
        blk: for (self.modules.values()) |module| {
            if (module.imports) |imports| {
                for (imports) |import| {
                    if (std.mem.eql(u8, name, import)) {
                        dependency_unused = false;
                        break :blk;
                    }
                }
            }
        }
        if (dependency_unused) {
            try self.writeLn("_ = dep_{s};", .{name}, .{});
        }
    }

    try self.writeLn("}}", .{}, .{ .indent = 0 });
}

fn writeItems(
    self: *ConfigBuildgen,
    comptime T: type,
    comptime writeItem: fn (*ConfigBuildgen, []const u8, T) anyerror!void,
    items: std.StringArrayHashMapUnmanaged(T),
) !void {
    const names = items.keys();
    const values = items.values();
    for (names, values) |name, item| {
        try writeItem(self, name, item);
        try self.writer.writeAll("\n");
    }
}

fn writeImports(
    self: *ConfigBuildgen,
    comptime T: type,
    items: std.StringArrayHashMapUnmanaged(T),
) !void {
    const keys = items.keys();
    const values = items.values();
    for (keys, values) |name, item| {
        const imports = switch (T) {
            Config.Module => item.imports orelse continue,
            else => blk: {
                const module_config = switch (item.root_module.value) {
                    .module => |m| m,
                    .name => continue,
                };
                break :blk if (module_config.imports) |imports| imports else continue;
            },
        };

        try self.writeImport(name, imports);
        try self.writer.writeAll("\n");
    }
}

pub fn writeOption(self: *ConfigBuildgen, name: []const u8, item: Config.Option) !void {
    const t, const default, const description = blk: switch (item.value) {
        .bool => |b| {
            break :blk .{
                "bool",
                if (b.default) |d| try std.fmt.allocPrint(self.allocator, "{}", .{d}) else null,
                b.description,
            };
        },
        .@"enum" => |e| {
            break :blk .{
                try std.fmt.allocPrint(self.allocator, "enum {s}", .{e.enum_options}),
                if (e.default) |d| try std.fmt.allocPrint(self.allocator, ".{s}", .{d}) else null,
                e.description,
            };
        },
        .enum_list => |e| {
            const enum_name = try std.fmt.allocPrint(self.allocator, "Enum{s}", .{try capitalize(name)});
            try self.writeLn("const {s} = enum {s};", .{ enum_name, e.enum_options }, .{});
            break :blk .{
                enum_name,
                if (e.default) |d| try std.fmt.allocPrint(self.allocator, "{s}", .{try enumSliceLiteral(enum_name, d)}) else null,
                e.description,
            };
        },
        .string => |s| {
            break :blk .{
                "[]const u8",
                if (s.default) |d| try std.fmt.allocPrint(self.allocator, "\"{s}\"", .{d}) else null,
                s.description,
            };
        },
        .list => |l| {
            break :blk .{
                "[][]const u8",
                try strSliceLiteral(l.default),
                l.description,
            };
        },
        .lazy_path => |l| {
            break :blk .{
                "std.Build.LazyPath",
                try lazyPath(l.default),
                l.description,
            };
        },
        .lazy_path_list => |l| {
            break :blk .{
                "[]std.Build.LazyPath",
                try lazyPathSlice(l.default),
                l.description,
            };
        },
        .build_id => |b| {
            break :blk .{
                "std.zig.BuildId",
                try buildId(b.default),
                b.description,
            };
        },
        .int => |i| {
            break :blk .{
                i.type,
                if (i.default) |d| try std.fmt.allocPrint(self.allocator, "{}", .{d}) else null,
                i.description,
            };
        },
        .float => |i| {
            break :blk .{
                i.type,
                if (i.default) |d| try std.fmt.allocPrint(self.allocator, "{}", .{d}) else null,
                i.description,
            };
        },
    };
    if (default) |d| {
        try self.writeLn(
            \\const option_{s} = b.option({s}, "{s}", "{s}") orelse {s};
        ,
            .{ name, t, name, description orelse "", d },
            .{},
        );
    } else {
        try self.writeLn(
            \\const option_{s} = b.option({s}, "{s}", "{s}");
        ,
            .{ name, t, name, description orelse "" },
            .{},
        );
    }

    try self.options.put(name, .{ .type_name = t, .optional = default == null });
}

pub fn writeOptionsModule(self: *ConfigBuildgen, name: []const u8, item: Config.OptionsModule) !void {
    try self.writeLn(
        "const options_{s} = b.addOptions();",
        .{name},
        .{},
    );

    for (item.map.keys(), item.map.values()) |option_name, value| {
        try self.writeOption(option_name, value);
        const option = self.options.get(option_name) orelse return error.MissingOption;
        try self.writeLn(
            \\options_{s}.addOption({s}{s}, "{s}", option_{s});
        ,
            .{ name, if (option.optional) "?" else "", option.type_name, option_name, option_name },
            .{},
        );
    }

    try self.writeLn(
        \\const options_module_{s} = options_{s}.createModule();
    ,
        .{ name, name },
        .{},
    );

    try self.options_modules.put(name, item);
}

pub fn writeModule(self: *ConfigBuildgen, name: []const u8, item: Config.Module) !void {
    try self.writeLn(
        \\const module_{s} = b.createModule(.{{
    ,
        .{name},
        .{},
    );

    try self.writeField("root_source_file", try lazyPath(item.root_source_file), .{ .quote_str = false });
    try self.writeField("target", try resolvedTarget(item.target), .{ .quote_str = false });
    try self.writeField("optimize", try optimize(item.optimize), .{ .quote_str = false });
    try self.writeField("link_libc", item.link_libc, .{});
    try self.writeField("link_libcpp", item.link_libcpp, .{});
    try self.writeField("single_threaded", item.single_threaded, .{});
    try self.writeField("strip", item.strip, .{});
    try self.writeField("unwind_tables", item.unwind_tables, .{});
    try self.writeField("dwarf_format", item.dwarf_format, .{});
    try self.writeField("code_model", item.code_model, .{});
    try self.writeField("stack_protector", item.stack_protector, .{});
    try self.writeField("stack_check", item.stack_check, .{});
    try self.writeField("sanitize_c", item.sanitize_c, .{});
    try self.writeField("sanitize_thread", item.sanitize_thread, .{});
    try self.writeField("fuzz", item.fuzz, .{});
    try self.writeField("valgrind", item.valgrind, .{});
    try self.writeField("pic", item.pic, .{});
    try self.writeField("red_zone", item.red_zone, .{});
    try self.writeField("omit_frame_pointer", item.omit_frame_pointer, .{});
    try self.writeField("error_tracing", item.error_tracing, .{});

    try self.writeLn("}});", .{}, .{});

    if (item.private orelse true) {
        try self.writeLn(
            \\b.modules.put(b.dupe("{s}"), module_{s}) catch @panic("OOM");
        ,
            .{ name, name },
            .{},
        );
    }
    try self.modules.put(name, item);
}

pub fn writeExecutable(self: *ConfigBuildgen, name: []const u8, item: Config.Executable) !void {
    const module_name = try self.allocModuleName(name, item.root_module);
    defer self.allocator.free(module_name);

    try self.writeLn(
        "const exe_{s} = b.addExecutable(.{{",
        .{name},
        .{},
    );

    try self.writeField("name", name, .{});
    try self.writeField("version", try semanticVersion(item.version), .{ .quote_str = false });
    try self.writeField("root_module", module_name, .{ .quote_str = false });
    try self.writeField("linkage", item.linkage, .{});
    try self.writeField("max_rss", item.max_rss, .{});
    try self.writeField("use_llvm", item.use_llvm, .{});
    try self.writeField("use_lld", item.use_lld, .{});
    try self.writeField("zig_lib_dir", try lazyPath(item.zig_lib_dir), .{ .quote_str = false });
    try self.writeField("win32_manifest", try lazyPath(item.win32_manifest), .{ .quote_str = false });

    try self.writeLn("}});", .{}, .{});
    try self.writer.writeAll("\n");

    try self.writeLn(
        \\const install_exe_{s} = b.addInstallArtifact(exe_{s}, .{{}});
        \\const install_tls_exe_{s} = b.step("build-exe:{s}", "Install the {s} executable");
        \\install_tls_exe_{s}.dependOn(&install_exe_{s}.step);
        \\b.getInstallStep().dependOn(&install_exe_{s}.step);
        \\
        \\const run_exe_{s} = b.addRunArtifact(exe_{s});
        \\if (b.args) |args| run_exe_{s}.addArgs(args);
        \\const run_tls_exe_{s} = b.step("run:{s}", "Run the {s} executable");
        \\run_tls_exe_{s}.dependOn(&run_exe_{s}.step);
    ,
        .{ name, name, name, name, name, name, name, name, name, name, name, name, name, name, name, name },
        .{},
    );
}

pub fn writeLibrary(self: *ConfigBuildgen, name: []const u8, item: Config.Library) !void {
    const module_name = try self.allocModuleName(name, item.root_module);
    defer self.allocator.free(module_name);

    try self.writeLn(
        "const lib_{s} = b.addLibrary(.{{",
        .{name},
        .{},
    );

    try self.writeField("name", name, .{});
    try self.writeField("version", try semanticVersion(item.version), .{ .quote_str = false });
    try self.writeField("root_module", module_name, .{ .quote_str = false });
    try self.writeField("linkage", item.linkage, .{});
    try self.writeField("max_rss", item.max_rss, .{});
    try self.writeField("use_llvm", item.use_llvm, .{});
    try self.writeField("use_lld", item.use_lld, .{});
    try self.writeField("zig_lib_dir", try lazyPath(item.zig_lib_dir), .{ .quote_str = false });
    try self.writeField("win32_manifest", try lazyPath(item.win32_manifest), .{ .quote_str = false });

    try self.writeLn("}});", .{}, .{});
    try self.writer.writeAll("\n");

    try self.writeLn(
        \\const install_lib_{s} = b.addInstallArtifact(lib_{s}, .{{}});
        \\const install_tls_lib_{s} = b.step("build-lib:{s}", "Install the {s} library");
        \\install_tls_lib_{s}.dependOn(&install_lib_{s}.step);
        \\b.getInstallStep().dependOn(&install_lib_{s}.step);
    ,
        .{ name, name, name, name, name, name, name, name },
        .{},
    );
}

pub fn writeObject(self: *ConfigBuildgen, name: []const u8, item: Config.Object) !void {
    const module_name = try self.allocModuleName(name, item.root_module);
    defer self.allocator.free(module_name);

    try self.writeLn(
        "const obj_{s} = b.addObject(.{{",
        .{name},
        .{},
    );

    try self.writeField("name", name, .{});
    try self.writeField("root_module", module_name, .{ .quote_str = false });
    try self.writeField("max_rss", item.max_rss, .{});
    try self.writeField("use_llvm", item.use_llvm, .{});
    try self.writeField("use_lld", item.use_lld, .{});
    try self.writeField("zig_lib_dir", try lazyPath(item.zig_lib_dir), .{ .quote_str = false });

    try self.writeLn("}});", .{}, .{});
    try self.writer.writeAll("\n");

    try self.writeLn(
        \\const install_obj_{s} = b.addInstallArtifact(obj_{s}, .{{}});
        \\const install_tls_obj_{s} = b.step("build-obj:{s}", "Install the {s} object");
        \\install_tls_obj_{s}.dependOn(&install_obj_{s}.step);
        \\b.getInstallStep().dependOn(&install_obj_{s}.step);
    ,
        .{ name, name, name, name, name, name, name, name },
        .{},
    );
}

pub fn writeTest(self: *ConfigBuildgen, name: []const u8, item: Config.Test) !void {
    const module_name = try self.allocModuleName(name, item.root_module);
    defer self.allocator.free(module_name);

    try self.writeLn(
        "const test_{s} = b.addTest(.{{",
        .{name},
        .{},
    );

    try self.writeField("name", name, .{});
    try self.writeField("root_module", module_name, .{ .quote_str = false });
    try self.writeField("max_rss", item.max_rss, .{});
    try self.writeField("use_llvm", item.use_llvm, .{});
    try self.writeField("use_lld", item.use_lld, .{});
    try self.writeField("zig_lib_dir", try lazyPath(item.zig_lib_dir), .{ .quote_str = false });
    try self.writeField("filters", try strSliceLiteral(item.filters), .{ .quote_str = false });

    try self.writeLn("}});", .{}, .{});

    try self.writeLn(
        \\const install_test_{s} = b.addInstallArtifact(test_{s}, .{{}});
        \\const install_tls_test_{s} = b.step("build-test:{s}", "Install the {s} test");
        \\install_tls_test_{s}.dependOn(&install_test_{s}.step);
        \\
        \\const run_test_{s} = b.addRunArtifact(test_{s});
        \\const run_tls_test_{s} = b.step("test:{s}", "Run the {s} test");
        \\run_tls_test_{s}.dependOn(&run_test_{s}.step);
        \\run_tls_test.dependOn(&run_test_{s}.step);
    ,
        .{ name, name, name, name, name, name, name, name, name, name, name, name, name, name, name },
        .{},
    );
}

pub fn writeFmt(self: *ConfigBuildgen, name: []const u8, item: Config.Fmt) !void {
    try self.writeLn(
        \\const fmt_{s} = b.addFmt(.{{
    ,
        .{name},
        .{},
    );

    try self.writeField("paths", try strSliceLiteral(item.paths) orelse "&.{}", .{ .quote_str = false });
    try self.writeField("exclude_paths", try strSliceLiteral(item.exclude_paths) orelse "&.{}", .{ .quote_str = false });
    try self.writeField("check", item.check, .{});

    try self.writeLn("}});", .{}, .{});
    try self.writer.writeAll("\n");

    try self.writeLn(
        \\const run_tls_fmt_{s} = b.step("fmt:{s}", "Run the {s} fmt");
        \\run_tls_fmt_{s}.dependOn(&fmt_{s}.step);
        \\run_tls_fmt.dependOn(&fmt_{s}.step);
    ,
        .{ name, name, name, name, name, name },
        .{},
    );
}

pub fn writeRun(self: *ConfigBuildgen, name: []const u8, item: Config.Run) !void {
    const Args = @import("Args.zig");

    const args = try Args.initFromString(self.allocator, item);
    defer args.deinit();

    try self.writeLn(
        \\const run_{s} = b.addSystemCommand({s});
        \\const run_tls_{s} = b.step("run:{s}", "Run the {s} run");
        \\run_tls_{s}.dependOn(&run_{s}.step);
    ,
        .{ name, (try strSliceLiteral(args.args.items)).?, name, name, name, name, name },
        .{},
    );
}

pub fn writeDependency(self: *ConfigBuildgen, name: []const u8, item: Config.Dependency) !void {
    _ = item;
    try self.writeLn(
        \\const dep_{s} = b.dependency("{s}", .{{}});
    ,
        .{ name, name },
        .{},
    );
    try self.dependencies.put(name, undefined);
}

pub fn writeImport(self: *ConfigBuildgen, name: []const u8, imports: [][]const u8) !void {
    for (imports) |import| {
        try self.writeLn(
            \\module_{s}.addImport("{s}", {s});
        ,
            .{ name, import, try self.resolveImport(import) },
            .{},
        );
    }
}

const WriteOpts = struct {
    indent: u8 = 4,
};

fn writeLn(self: *ConfigBuildgen, comptime fmt: []const u8, args: anytype, comptime opts: WriteOpts) !void {
    // first format the string
    const str = try std.fmt.allocPrint(self.allocator, fmt, args);
    defer self.allocator.free(str);

    // then add indentation + newlines
    var it = std.mem.splitScalar(u8, str, '\n');
    while (it.next()) |line| {
        if (line.len == 0) {
            try self.writer.writeAll("\n");
        } else {
            try self.writer.print("{s}{s}\n", .{ [_]u8{' '} ** opts.indent, line });
        }
    }
}

const WriteFieldOpts = struct {
    indent: u8 = 8,
    quote_str: bool = true,
};

fn writeFields(self: *ConfigBuildgen, kvs: anytype, comptime opts: WriteFieldOpts) !void {
    for (kvs) |kv| {
        self.writeField(kv[0], kv[1], opts);
    }
}

fn writeField(self: *ConfigBuildgen, key: []const u8, value: anytype, comptime opts: WriteFieldOpts) !void {
    const value_typ1 = @typeInfo(@TypeOf(value));
    const value_typ, const value_ = if (value_typ1 == .optional) blk: {
        if (value == null) {
            return;
        }
        break :blk .{ @typeInfo(value_typ1.optional.child), value.? };
    } else .{ value_typ1, value };

    const value_str = switch (value_typ) {
        .@"enum" => try std.fmt.allocPrint(self.allocator, ".{}", .{std.zig.fmtId(@tagName(value_))}),
        .bool => if (value_) "true" else "false",
        .int => try std.fmt.allocPrint(self.allocator, "{d}", .{value_}),
        // string
        .pointer => |p| blk: {
            if (p.size == .slice) {
                const childInfo = @typeInfo(p.child);
                if (childInfo == .int and childInfo.int.bits == 8) {
                    if (opts.quote_str) {
                        break :blk try std.fmt.allocPrint(self.allocator, "\"{s}\"", .{value_});
                    } else {
                        break :blk value_;
                    }
                }
            }
            return error.InvalidType;
        },
        else => return error.InvalidType,
    };

    try self.writeLn(
        ".{s} = {s},",
        .{
            key,
            value_str,
        },
        .{ .indent = opts.indent },
    );
}

/// return the module name, writing the module definition first if necessary
fn allocModuleName(self: *ConfigBuildgen, name: []const u8, item: Config.ModuleLink) ![]const u8 {
    return try std.fmt.allocPrint(
        self.allocator,
        "module_{s}",
        .{switch (item.value) {
            .name => |n| n,
            .module => |m| blk: {
                const n = m.name orelse name;
                try self.writeModule(n, m);
                try self.writer.writeAll("\n");
                break :blk n;
            },
        }},
    );
}

/// used for temp strings
/// This is safe because only a single consumer of scratch exists at a time
threadlocal var scratch: [4096]u8 = undefined;

fn capitalize(s: []const u8) ![]const u8 {
    if (s.len == 0) {
        return s;
    }
    return try std.fmt.bufPrint(
        &scratch,
        "{c}{s}",
        .{ std.ascii.toUpper(s[0]), s[1..] },
    );
}

fn lazyPath(path: ?[]const u8) !?[]u8 {
    if (path) |p| {
        return try std.fmt.bufPrint(
            &scratch,
            "b.path(\"{s}\")",
            .{p},
        );
    } else {
        return null;
    }
}
fn lazyPathSlice(paths_maybe: ?[][]const u8) !?[]u8 {
    if (paths_maybe) |paths| {
        var w = std.io.fixedBufferStream(&scratch);
        const writer = w.writer();

        try writer.writeAll("&[_]std.Build.LazyPath{ ");

        for (paths, 0..) |path, i| {
            try writer.print("b.path(\"{s}\")", .{path});
            if (i != paths.len - 1) {
                try writer.writeAll(", ");
            }
        }

        try writer.writeAll(" }");
        return w.getWritten();
    } else {
        return null;
    }
}
fn buildId(build_id: ?[]const u8) !?[]const u8 {
    if (build_id) |b| {
        return try std.fmt.bufPrint(
            &scratch,
            \\std.zig.BuildId.parse("{s}") catch @panic("invalid build id")
        ,
            .{b},
        );
    } else {
        return null;
    }
}

fn resolvedTarget(target: ?[]const u8) ![]const u8 {
    if (target) |t| {
        return try std.fmt.bufPrint(
            &scratch,
            \\b.resolveTargetQuery(std.Target.Query.parse(.{{.arch_os_abi = "{s}"}}) catch @panic("invalid target"))
        ,
            .{t},
        );
    } else {
        return @constCast("target");
    }
}

fn optimize(opt: ?std.builtin.OptimizeMode) ![]const u8 {
    if (opt) |o| {
        return try std.fmt.bufPrint(
            &scratch,
            \\.{s}
        ,
            .{@tagName(o)},
        );
    } else {
        return @constCast("optimize");
    }
}

fn semanticVersion(version: ?[]const u8) !?[]u8 {
    if (version) |v| {
        return try std.fmt.bufPrint(
            &scratch,
            "std.SemanticVersion.parse(\"{s}\") catch @panic(\"invalid version\")",
            .{v},
        );
    } else {
        return null;
    }
}

pub fn strSliceLiteral(str_slice_maybe: ?[]const []const u8) !?[]u8 {
    if (str_slice_maybe) |str_slice| {
        var w = std.io.fixedBufferStream(&scratch);
        const writer = w.writer();

        try writer.writeAll("&[_][]const u8{ ");

        for (str_slice, 0..) |str, i| {
            try writer.print("\"{s}\"", .{str});
            if (i != str_slice.len - 1) {
                try writer.writeAll(", ");
            }
        }

        try writer.writeAll(" }");
        return w.getWritten();
    } else {
        return null;
    }
}

pub fn strTupleLiteral(str_slice_maybe: ?[]const []const u8) !?[]u8 {
    if (str_slice_maybe) |str_slice| {
        var w = std.io.fixedBufferStream(&scratch);
        const writer = w.writer();

        try writer.writeAll(".{ ");

        for (str_slice, 0..) |str, i| {
            try writer.print("\"{s}\"", .{str});
            if (i != str_slice.len - 1) {
                try writer.writeAll(", ");
            }
        }

        try writer.writeAll(" }");
        return w.getWritten();
    } else {
        return null;
    }
}

fn enumSliceLiteral(enum_name: []const u8, enum_slice: []const []const u8) ![]u8 {
    var w = std.io.fixedBufferStream(&scratch);
    const writer = w.writer();

    try writer.print("&[_]{s}{{ ", .{enum_name});

    for (enum_slice, 0..) |enum_value, i| {
        try writer.print(".{s}", .{enum_value});
        if (i != enum_slice.len - 1) {
            try writer.writeAll(", ");
        }
    }

    try writer.writeAll(" }");
    return w.getWritten();
}

fn resolveImport(self: *ConfigBuildgen, import: []const u8) ![]const u8 {
    var w = std.io.fixedBufferStream(&scratch);
    const writer = w.writer();
    if (self.modules.contains(import)) {
        try writer.print("b.modules.get(\"{s}\") orelse @panic(\"missing module {s}\")", .{ import, import });
    } else if (self.options_modules.contains(import)) {
        try writer.print("options_module_{s}", .{import});
    } else if (self.dependencies.contains(import)) {
        try writer.print("dep_{s}.module(\"{s}\")", .{ import, import });
    } else {
        try writer.print("@panic(\"missing import {s}\")", .{import});
    }

    return w.getWritten();
}
